### ISSUE TITLE
tn-types: the test-utils feature enables clap and tracing-subscriber without the features it uses

### ISSUE THREAD

**Issue by grantkee** [Telcoin-Association/telcoin-network#1406]
## Summary

`tn-types`' `test-utils` feature turns its two optional dependencies on but enables none of the dependency features the gated code actually uses, so the feature does not compile on its own. It is masked today because every build that exercises it also compiles `tn-types`' dev-dependencies, which happen to supply the missing features through cargo's feature unification.

## Repro

```
$ cargo check -p tn-types --features test-utils --lib
error: cannot find derive macro `Parser` in this scope
error: cannot find attribute `clap` in this scope
error[E0433]: failed to resolve: could not find `EnvFilter` in `tracing_subscriber`
error[E0433]: failed to resolve: could not find `fmt` in `tracing_subscriber`
error[E0425]: cannot find function `fmt` in crate `tracing_subscriber`
error: could not compile `tn-types` (lib) due to 5 previous errors
```

## Cause

`crates/types/Cargo.toml:55`:

```toml
test-utils = ["tracing-subscriber", "clap"]
```

Both are enabled without features, and the workspace pins them without what the code needs (root `Cargo.toml:73,78`):

```toml
clap = "4"                                                             # no `derive`
tracing-subscriber = { version = "0.3.20", default-features = false }  # no `fmt`, no `env-filter`
```

while the `test-utils`-gated code uses exactly those:

- `crates/types/src/test_utils/tracing.rs:6-8` — `tracing_subscriber::fmt()`, `tracing_subscriber::EnvFilter`, `tracing_subscriber::fmt::format::FmtSpan`
- `crates/types/src/test_utils/mod.rs:10` — `#[clap(flatten)]`, under a `derive(Parser)`

## Why nothing catches it

`tn-types`' own dev-dependencies mask it. `tn-storage` (with `test-utils`) and `tn-test-utils-committee` pull `clap` and `tracing-subscriber` with the missing features, and cargo unifies features per build — so any build that compiles dev-dependencies succeeds, and only a lib-only build fails:

| command | dev-deps compiled | result |
|---|---|---|
| `cargo check -p tn-types --features test-utils --lib` | no | **fails** |
| `cargo check -p tn-types --features test-utils --all-targets` | yes | passes |
| `cargo test -p tn-types --features test-utils` | yes | passes |
| `make test` / `make check` (`--workspace`) | yes | passes |

So the declared feature set is wrong, but no lane in CI is narrow enough to exercise it.

## Impact

Low severity, no runtime effect — but the feature does not stand on its own, which makes it a footgun in two ways. A consumer depending on `tn-types` with `test-utils` that does not happen to pull the same transitive features gets an unexplained build failure inside someone else's crate. And any future narrowly scoped lane (`-p tn-types --lib`) fails for a reason unrelated to whatever it was added to check.

## Suggested fix

Have the feature enable what the code uses:

```toml
test-utils = [
    "dep:tracing-subscriber",
    "tracing-subscriber/fmt",
    "tracing-subscriber/env-filter",
    "dep:clap",
    "clap/derive",
]
```

Worth confirming the exact feature names against the pinned versions (`fmt` and `env-filter` both imply `std` in tracing-subscriber 0.3). Then add `cargo check -p tn-types --features test-utils --lib` to a lane so the declaration cannot drift back.

## Provenance

Surfaced while reviewing the governance-Safe fork branch (`feat/governance-safe-fork`). Pre-existing and unrelated to it: that branch touches neither the root/`tn-types` `Cargo.toml` nor `crates/types/src/test_utils/`, and the failure reproduces identically on `main`.
