### ISSUE TITLE
main does not compile - stale .is_some() on an unwrapped u64 in request_epoch_pack_inner (regression from #810)

### ISSUE THREAD

**Issue by Huwonk** [Telcoin-Association/telcoin-network#821]
`origin/main` at `ea2cc368` does not compile under default features:

```
error[E0599]: no method named `is_some` found for type `u64`
  --> crates/consensus/primary/src/network/mod.rs:810
```

## Root cause

#810 (`ea2cc368`, "drop the legacy full-pack sync fallback") added an early return in `request_epoch_pack_inner` that rebinds `last_consensus_number` from `Option<u64>` to `u64`:

```rust
// crates/consensus/primary/src/network/mod.rs:729
let Some(last_consensus_number) = last_consensus_number else {
    return self.request_epoch_pack_sync(...).await;
};
```

The `if last_consensus_number.is_some()` further down (line 810, from the earlier commit `4cae59c1`) was not updated, so it now calls `.is_some()` on a `u64`.

## Impact

main does not build, so the local attest gate (`etc/test-and-attest.sh`, which runs `clippy -D warnings` and the full test suite) fails for anything merged up to current main. This blocks attesting other branches.

## Suggested fix

Past the early return we are always in the partial-prefix case, so the `else` branch (legacy `stream_import`) is unreachable. Collapse to an unconditional import:

```rust
let import_result = consensus_chain
    .import_partial_to_staging(stream.compat(), epoch_record, previous_epoch, record_timeout)
    .await;
```

Verified locally: with this change `cargo check --workspace --all-targets` under `RUSTFLAGS="-D warnings"` is clean. `stream_import` is still used elsewhere, so this creates no dead code. Flagging for the #810 author to confirm the intended behavior.
